eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # Server url is set to below
      defaultZone: http://localhost:8761


spring:
  application:
    name: sms-discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URI}